version: '3.8'
services:
  it_bot:
    image: skyline8880/it_bot:latest
    container_name: it_bot
    restart: on-failure
    environment:
      - TZ=Europe/Moscow
    env_file:
      - .env
    ports:
      - 120:80